---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ministryofjustice/analytical-platform-ollamate
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  name: "ollamate"
  annotations: {}

podAnnotations: {}
podLabels: {}
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "default"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: ollamate.compute.development.analytical-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ollamate-tls
      hosts:
        - ollamate.compute.development.analytical-platform.service.justice.gov.uk

app:
  image:
    repository: ghcr.io/ministryofjustice/analytical-platform-ollamate
    pullPolicy: IfNotPresent
    tag: ""
  environment:
    - name: APP_ENVIRONMENT
      valueFrom:
        secretKeyRef:
          name: ollamate-app-secrets
          key: environment
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: ollamate-app-secrets
          key: secret_key
    - name: DJANGO_SETTINGS_MODULE
      value: ollamate.settings
    - name: ALLOWED_HOSTS
      value: "*"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: ollamate-rds
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ollamate-rds
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: ollamate-rds
          key: address
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: ollamate-rds
          key: port
    - name: DB_NAME
      value: "ollamate"
    # - name: SENTRY_DSN
    #   valueFrom:
    #     secretKeyRef:
    #       name: ollamate-sentry-dsn
    #       key: dsn
  port: 8000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000

reverseProxy:
  image:
    repository: "docker.io/nginxinc/nginx-unprivileged"
    tag: "1.27.0-alpine3.19"
  port: 8080
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 101

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
              operator: In
              values:
                - gpu-on-demand

tolerations:
  - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
    operator: "Equal"
    value: gpu-on-demand
    effect: "NoSchedule"

ephemeral:
  enabled: true
  cron:
    timezone: Europe/London
    start: "0 7 * * *"
    end: "30 18 * * *"
    desiredReplicas: 1
