---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ministryofjustice/analytical-platform-ollamate
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10000

resources:
  requests:
    cpu: 1
    memory: "2Gi"
  limits:
    cpu: 2
    memory: "4Gi"
