FROM docker.io/ollama/ollama:latest

RUN <<EOF
# Start Ollama
nohup ollama serve &

# Wait for Ollama to start
sleep 15

# Pull model
ollama pull llama3

# Kill Ollama process
kill -9 $(ps aux | grep "ollama" | grep -v "grep" | awk '{print $2}')
EOF
