[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = '''
/(
    \.git
    env
    venv
    | migrations
)/
'''


[tool.isort]
profile = 'black'
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
line_length = 100
multi_line_output = 3
