apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytical-platform-ollamate.fullname" . }}
  labels:
    {{- include "analytical-platform-ollamate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.reverseProxy.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "analytical-platform-ollamate.selectorLabels" . | nindent 4 }}
