---
name: Enforce Version Pinning

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  enforce-version-pinning:
    name: Enforce Version Pinning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Check for pinned versions in requirements.txt
        run: |
          if grep -q -v '==' requirements.txt; then
            echo "Unpinned dependencies found in requirements.txt"
            echo "❌ Unpinned dependencies found in requirements.txt"
            exit 1
          else
            echo "✅ All dependencies are correctly pinned."
          fi

      - name: Check for pinned versions in package.json
        run: |
          UNPINNED=$(grep -E '"[^"]+": "\^|~' package.json || true)
          if [ -n "$UNPINNED" ]; then
            echo "❌ Unpinned dependencies found in package.json:"
            echo "$UNPINNED"
            exit 1
          else
            echo "✅ All dependencies are correctly pinned."
          fi
